name: DeluxeMenusItems
version: 1.2.1
main: it.rhalis.deluxemenusitems.DeluxeMenusItems
depend: [DeluxeMenus]
authors: [RhalisX99]
description: Open your DeluxeMenus' menus with an item in your hand
commands:
  deluxemenusitems:
    description: DeluxeMenusItems Admin command